- name: Parse url
  ansible.builtin.set_fact:
    url_parse: "{{ git_url | parse_url }}"

- name: Clear destination path
  ansible.builtin.file:
    path: "{{ dest_path }}"
    state: absent
  changed_when: false

- name: Get policies from git
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ dest_path }}"
  changed_when: false
