- name: get policy
  uri:
    url: https://{{ acs_host }}/v1/policies/{{ policy.id }}
    headers:
      Authorization: "Bearer {{ acs_token }}"
    method: GET
    status_code: 200
    validate_certs: false
  register: policy_body
  no_log: true

- name: write policy {{ policy_body.json.name }}
  copy:
    # filter lastUpdated out of the policy body
    content: '{{ policy_body.json | dict2items | rejectattr("key", "eq", "lastUpdated") | list | items2dict }}'
    dest: 'files/policies_actual/{{ policy_body.json.name | replace("/", " ") | replace(":", " ") }}.json'
  changed_when: false