- name: Update policy if bodies dont match
  ansible.builtin.uri:
    url: https://{{ acs_host }}/v1/policies/{{ policy_body.id }}
    headers:
      Authorization: "Bearer {{ acs_token }}"
    method: PUT
    body: '{{ desired_policy_body }}'
    force_basic_auth: true
    status_code: 200
    body_format: json
    validate_certs: false
  register: answer
  no_log: false
  changed_when: true
  notify: "Push to git"
